/* eslint-disable */
// @ts-nocheck
// This file is auto-generated by the flowbite-react CLI.
// Edit .flowbite-react/config.json instead of editing this file directly.

import { StoreInit } from 'flowbite-react/store/init';
import React from 'react';

export const CONFIG = {
  dark: true,
  prefix: '',
  version: 4,
};

export function ThemeInit() {
  return <StoreInit {...CONFIG} />;
}

ThemeInit.displayName = 'ThemeInit';
